### ISSUE TITLE
Non html version

### ISSUE THREAD

**Issue by chrisoro** [plenarius/iota-promoter#1]
Can you create a standalone js that runs without the html stuff? Basically like that autorun which happens after you open the page.

This way, you can run it on a server using nodejs

**Comment by plenarius** [comment]
I'm not too familiar with js to do that but I'm definitely doing one with the python api, I'm just waiting for [this issue for promotion](https://github.com/iotaledger/iota.lib.py/issues/121) to be incorporated then I'll get one done in python that can be ran server side.
